# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\"6\n\x10LoginUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"$\n\x11LoginUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"9\n\x13RegisterUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\'\n\x14RegisterUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0eGetInfoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x0fGetInfoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb0\x01\n\tSimpleApp\x12\x34\n\tLoginUser\x12\x11.LoginUserRequest\x1a\x12.LoginUserResponse\"\x00\x12=\n\x0cRegisterUser\x12\x14.RegisterUserRequest\x1a\x15.RegisterUserResponse\"\x00\x12.\n\x07GetInfo\x12\x0f.GetInfoRequest\x1a\x10.GetInfoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LOGINUSERREQUEST']._serialized_start=13
  _globals['_LOGINUSERREQUEST']._serialized_end=67
  _globals['_LOGINUSERRESPONSE']._serialized_start=69
  _globals['_LOGINUSERRESPONSE']._serialized_end=105
  _globals['_REGISTERUSERREQUEST']._serialized_start=107
  _globals['_REGISTERUSERREQUEST']._serialized_end=164
  _globals['_REGISTERUSERRESPONSE']._serialized_start=166
  _globals['_REGISTERUSERRESPONSE']._serialized_end=205
  _globals['_GETINFOREQUEST']._serialized_start=207
  _globals['_GETINFOREQUEST']._serialized_end=235
  _globals['_GETINFORESPONSE']._serialized_start=237
  _globals['_GETINFORESPONSE']._serialized_end=271
  _globals['_SIMPLEAPP']._serialized_start=274
  _globals['_SIMPLEAPP']._serialized_end=450
# @@protoc_insertion_point(module_scope)
